- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/services/AttributeServices.java
This change adds a new default method the interface which can be used
to write a single value. It is a convenience method for "writeValues"
which requires a list as argument and returns a list as result.
---
This would be the pendant to `readValue`.
> Added a default method to write a single value

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/subscriptions/UaSubscriptionManager.java
The interface SubscriptionListener now provides empty default methods
so that consumers of the events can choose to only implement methods
which are relevant for them.
----
I added the empty default to all methods since sometimes users might just be interested in "the other" event and then you would still have a few empty declarations required.
> #19: let the SubscriptionListener interface provide default methods

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/config/OpcUaClientConfig.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/config/OpcUaServerConfig.java
- opc-ua-sdk/sdk-server/src/test/java/org/eclipse/milo/opcua/sdk/server/api/config/OpcUaServerConfigTest.java
- opc-ua-sdk/sdk-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/config/OpcUaClientConfigTest.java
- opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/config/UaTcpStackClientConfig.java
- opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/config/UaTcpStackServerConfig.java
- opc-ua-stack/stack-tests/src/test/java/org/eclipse/milo/opcua/stack/client/config/UaTcpStackClientConfigTest.java
Adds copy() methods to the client and server config objects that allow for easier copying and modification of an existing config.
> [#17] copy() methods for config objects

- opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/tcp/SocketServer.java
- opc-ua-stack/stack-tests/src/test/java/org/eclipse/milo/opcua/stack/server/tcp/SocketServerTest.java
Once a SocketServer is no longer used by any UaTcpStackServers it should be shut down and removed to prevent leaking SocketServer instances.
> [#23] shut down and remove unused SocketServers

- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/serialization/DelegateRegistry.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/serialization/OpcUaDataTypeEncoding.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/serialization/binary/BinaryDecoder.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/serialization/binary/BinaryEncoder.java
Ensure the registry cannot be queried for encoders and decoders until
the initial scan for the built-in types and their corresponding
delegates has finished.
> [#30] Add synchronization to DelegateRegistry initialization

- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/serialization/binary/BinaryDecoder.java
- opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/serialization/binary/VariantSerializationTest.java
A variant containing a null array value that was encoded by setting the array length bit in the encoding mask and using a -1 array size caused a NegativeArraySizeException.
> [#45] fix issue decoding Variant with null array

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/subscriptions/UaSubscription.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/subscriptions/UaSubscriptionManager.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscription.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscriptionManager.java
- opc-ua-sdk/sdk-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/OpcUaClientIT.java
Adds new callbacks to SubscriptionListener that allow for data and event notifications to be received at the subscription-level rather than per-item, if desired.
> New subscription-level data change callbacks

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscriptionManager.java
The recent change to preserve the distinction between null and empty arrays while decoding (as per the spec) has lead to instances where a previously always-empty array is now null depending on the server implementation, leading to NPEs.
> [#63] Fix NPE in OpcUaSubscriptionManager

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/SessionManager.java
If the client doesn't provide any client software certificate, the list is null and causes a NPE.
Fixed with this commit
> Fix NPE if clientSoftwareCertificates is null

- .gitignore
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/config/OpcUaServerConfigBuilder.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/AnonymousIdentityValidator.java
- opc-ua-sdk/sdk-server/src/test/java/org/eclipse/milo/opcua/sdk/server/api/config/OpcUaServerConfigTest.java
This change provides a static instance for the 
AnonymousIdentityValidator and deprecates the default constructor.
Signed-off-by: Jens Reimann <jreimann@redhat.com>
> #74: Provide a static instance of AnonymousIdentityValidator

- milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleNamespace.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/AccessContext.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/ViewManager.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/namespaces/OpcUaNamespace.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/namespaces/VendorNamespace.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/ViewServices.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/helpers/BrowseHelper.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/helpers/BrowsePathsHelper.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/util/NoOpNamespace.java
- opc-ua-sdk/sdk-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/TestNamespace.java
Provides an `AccessContext` that can be used to identify the session or user associated with a browse request.
Issue #93 
@AriSuutariST
> Provide AccessContext to browse calls

- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/ByteString.java
This way all values/ID of a NodeId and the NodeId itself would be
serializable.
Signed-off-by: Jens Reimann <jreimann@redhat.com>
> Make the ByteString serializable

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/OpcUaServer.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/Session.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/SessionManager.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/AttributeHistoryManager.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/AttributeManager.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/Namespace.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/AttributeHistoryServices.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/util/PendingHistoryRead.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/util/PendingHistoryUpdate.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/application/UaStackServer.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/application/services/AttributeHistoryServiceSet.java
This adds functionality that is required to get the historyRead request to arrive at namespace implementation. It works for me, but I'm not happy about the default historyRead implementation
in AtttributeManager, which just returns StatusCode.BAD for all requested items. I guess it should be polished to return Bad_NotSupported at operation level (but that wouldn't be perfect either, because there might be one namespace that supports history and another that doesn't).
Signed-off-by: Ari Suutari <ari.suutari@syncrontech.com>
> Add (some) support for historyRead and historyUpdate operations.

- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/QualifiedName.java
- opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/types/builtin/QualifiedNameTest.java
I think there is a bug in the qualified name parsing. It looks to me as if only the first colon should be special. However I didn't check that in the spec. @kevinherron you might know this.
> Fix handling of colons in qualified names

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/config/OpcUaClientConfig.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/config/OpcUaClientConfigBuilder.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/OpcUaServer.java
- opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/config/UaTcpStackClientConfig.java
- opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/config/UaTcpStackClientConfigBuilder.java
- opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/handlers/UaTcpClientAcknowledgeHandler.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/application/CertificateManager.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/application/DefaultCertificateManager.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/channel/ChunkEncoder.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/channel/ClientSecureChannel.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/channel/SecureChannel.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/channel/ServerSecureChannel.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/CertificateUtil.java
- opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/application/DefaultCertificateManagerTest.java
- opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/handlers/UaTcpServerAsymmetricHandler.java
- opc-ua-stack/stack-tests/src/test/java/org/eclipse/milo/opcua/stack/SecureChannelFixture.java
- opc-ua-stack/stack-tests/src/test/java/org/eclipse/milo/opcua/stack/client/config/UaTcpStackClientConfigTest.java
Client certificate chains are configured in the UaTcpStackClientConfig.
Server certificate chains are configured in the CertificateManager that
UaTcpStackServerConfig provides.
> Add support for configuring a certificate chain on client and server

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/OpcUaClient.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/UaClient.java
This change allows to actually receive the OpcUaClient type when the client supports that:
```java
public CompletableFuture<OpcUaClient> createClient() { … }
// before
public static CompletableFuture<UaClient> connect() {
return createClient().thenCompose(client -> client.connect());
}
// after
public static CompletableFuture<OpcUaClient> connect() {
return createClient().thenCompose(client -> client.connect());
}
```
> Allow receiving the OpcUaClient type

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/subscriptions/UaSubscriptionManager.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscriptionManager.java
When not explicitly specified by the user, recalculate the max keep-alive count and lifetime count values when a subscription is created or modified and the publishing interval is revised.
This primarily allows for reasonable values to be established when the original requested publishing interval was 0, since reasonable values can't be calculated until the revised publishing interval is known.
>  Recalculate keep-alive count when publishing interval is revised

- milo-examples/client-examples/pom.xml
- milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/ClientExampleRunner.java
- milo-examples/server-examples/pom.xml
- milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleServer.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/identity/UsernameProvider.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/identity/X509IdentityProvider.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/UsernameIdentityValidator.java
- opc-ua-sdk/sdk-tests/pom.xml
- opc-ua-sdk/sdk-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/OpcUaClientIT.java
- opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/handlers/UaTcpClientMessageHandler.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/channel/SecureChannel.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/security/SecurityAlgorithm.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/security/SecurityPolicy.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/NonceUtil.java
- opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/handlers/UaTcpServerAsymmetricHandler.java
- opc-ua-stack/stack-tests/pom.xml
- opc-ua-stack/stack-tests/src/test/java/org/eclipse/milo/opcua/stack/ChunkSerializationTest.java
- opc-ua-stack/stack-tests/src/test/java/org/eclipse/milo/opcua/stack/ClientServerTest.java
- opc-ua-stack/stack-tests/src/test/java/org/eclipse/milo/opcua/stack/SecureChannelFixture.java
Implements two new security profiles:
* Aes128_Sha256_RsaOaep
* Aes256_Sha256_RsaPss
These profiles are intended to be replacements for all existing profiles
except Basic256Sha256, which is the only profile that does not currently
rely on SHA1 in a way that endangers security (if only yet theoretical).
> Implement new Sha2-based security profiles

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscriptionManager.java
Sending a new PublishRequest immediately effectively disables the
back-pressure mechanism built into the OPC UA subscription model. By
processing the notification before sending a new request we ensure that
data changes never arrive faster than the client can process them.
> Wait until after notification delivery to send another PublishRequest

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/nodes/UaNode.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscriptionManager.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/SessionManager.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/DefaultAttributeHistoryServiceSet.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/util/AttributeReader.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/serialization/OpcUaXmlStreamDecoder.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/serialization/OpcUaXmlStreamEncoder.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/DataTypeEncoding.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/OpcUaDefaultBinaryEncoding.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/OpcUaDefaultXmlEncoding.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/ExtensionObject.java
Encode, decode, and transcode methods now accept an EncodingLimits in
their most verbose overload.
> [#216] allow EncodingLimits to be used with ExtensionObjects

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/states/AbstractSessionState.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/SessionManager.java
- opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/handlers/UaTcpServerAsymmetricHandler.java
This already happens when secure channels are created, but if/when Milo
adds support for other transports, such as HTTPS, then it's necessary
that the validation happens during session creation because there may
be no earlier opportunity.
> Validate certificates and verify trust chain during session creation

- opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/handlers/UaTcpClientAcknowledgeHandler.java
- opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/handlers/UaTcpClientMessageHandler.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/Stack.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/channel/headers/HeaderDecoder.java
- opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/handlers/RateLimitingHandler.java
- opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/handlers/UaTcpServerAsymmetricHandler.java
- opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/handlers/UaTcpServerHelloHandler.java
- opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/handlers/UaTcpServerSymmetricHandler.java
- opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/tcp/SocketServers.java
Implements some basic DoS mitigations:
1) Rate limit inbound connection attempts on a per-remote-address basis. This does not include connections from localhost.
2) Check the message length indicated in the header against max chunk size ASAP. This prevents a maliciously crafted length and buffer from growing beyond max chunk size, as opposed to letting it grow and catching it when the chunk is handled.
3) Limit the number of total connections and connections per remote address.
4) Implement a deadline for receiving the UA TCP Hello message after a connection is established.
> DoS Mitigations

- milo-examples/standalone-examples/README.md
Saw the discussion on gitter about the wrong names of the maven profiles, updates these and added more info about the two examples and their differences.
> Update readme with correct names of profiles and info about user database

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/factories/BrowsePath.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/factories/InstanceDeclarationHierarchy.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/factories/ReferenceTable.java
Always use namespace 0 for BrowsePath that represents the root of a
hierarchy so equality check works even when the type hierarchy spans
multiple namespaces.
fixes #350
> Use a fixed namespace for root BrowsePath when building type hierarchy

- milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/ProsysEventSubscriptionExample.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/states/SessionState.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/application/CertificateValidator.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/application/DefaultCertificateValidator.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/PShaUtil.java
I believe there is "maven" checking of checkstyle, but by default eclipse import of the projects, the below cause errors. I believe they are not harmful, and we can add checkstyle checks in Eclipse to match maven, at a later point.
Signed-off-by: Ahmed Ashour <asashour@yahoo.com>
> Fix eclipse checkstyle errors

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/config/OpcUaClientConfig.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/config/OpcUaClientConfigBuilder.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/states/AbstractSessionState.java
- opc-ua-sdk/sdk-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/config/OpcUaClientConfigTest.java
Currently, session's preferred localeIds are set to none (empty array). With this modification they default to none, but they can be configured by calling OpcUaClientConfigBuilder.setSessionLocaleIds()
Signed-off-by: igarciasz <ignacio.garcia@tecnalia.com>
> Configurable LocaleIds when activateSession

- .gitignore
Running TestNG tests in Eclipse produces files in `test-output`, and these are considered for commits, it should be ignored.
Signed-off-by: Ahmed Ashour <asashour@yahoo.com>
> ignore test-output folders

- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/EndpointUtil.java
- opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/util/EndpointUtilTest.java
This allows it to extract paths from URLs that Java's URI class deems
invalid like other methods do.
> Refactor EndpointUtil.getPath() to use regex instead of Java's URI

- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/SelfSignedCertificateGenerator.java
> Use Locale.ENGLISH for dates when generating self-signed certificates

- opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/transport/uasc/UascClientAcknowledgeHandler.java
- opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/transport/uasc/UascClientMessageHandler.java
- opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/transport/uasc/UascServerAsymmetricHandler.java
- opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/transport/uasc/UascServerHelloHandler.java
- opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/transport/uasc/UascServerSymmetricHandler.java
This prevents sequence numbers from being processed out of order when 
two or more messages, starting with an OPN for a secure channel renewal,
arrive at the same time and are all ready to be decoded.
Implement `decode` consistently among all the handlers, allowing Netty
to be responsible for looping until no more messages can be read.
fixes #483
> Pass messages to next the handler using ctx.fireChannelRead()

- build-tools/src/main/resources/milo/checkstyle.xml
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/AbstractIdentityValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/AbstractUsernameIdentityValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/AbstractX509IdentityValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/AnonymousIdentityValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/CompositeValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/IdentityValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/UsernameIdentityValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/X509IdentityValidator.java
Add type parameter to IdentityValidator API and implement reusable abstract base classes for anonymous, username, and X509 validators.
> Add type parameter to IdentityValidator API

- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/EndpointUtil.java
- opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/util/EndpointUtilTest.java
This isn't recognizing or validating IPv6 addresses so much as just
allowing the possibility of an IPv6 address in the hostname position by
allowing anything inside a pair of square brackets to be treated as a
hostname.
fixes #509
> Naive support for IPv6 addresses in EndpointUtil

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/OpcUaClient.java
If the OPC-UA Server returns a NamespaceTable containing more
than 65535 items, client throws a NumberFormatException
when converting the index to ushort.
Added warning for that scenario and limit on the number of
namespaces added to the local table.
> Add limit to NamespaceTable length when connecting

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/SessionFsmFactory.java
Code that accessed the SessionFsm in a blocking manner while in a
callback from the FSM could deadlock:
```
client.connect().thenRun(() -> {
try {
client.disconnect().get();
} catch (InterruptedException | ExecutionException e) {
e.printStackTrace();
}
}).get();
```
fixes #560
> Complete SessionFsm futures asynchronously to avoid deadlocks

- milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/SubscriptionExample.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/subscriptions/UaSubscription.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscription.java
- opc-ua-sdk/sdk-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/subscriptions/ClientHandleSequenceTest.java
This sequence handles rollover and ensuring that after rollover only
client handles not currently being used are returned.
> Provide a unique-per-UaSubscription sequence of client handles 

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/identity/UsernameProvider.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/identity/X509IdentityProvider.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/SessionFsmFactory.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/SessionManager.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/NonceUtil.java
Nonce validation can be relaxed when:
- using an AnonymousIdentityToken
- using a UserNameIdentityToken with SecurityPolicy None in both the channel
and UserTokenPolicy
- using an X509IdentityToken with SecurityPolicy None in both the channel and
UserTokenPolicy
This allows unsecured credentials to be used regardless of the nonce validity,
since the nonce isn't used in that case, while still ensuring that if the nonce
is supposed to protect the credentials it must be valid.
fixes #579
> Relax nonce validation when not used to protect credentials

- milo-examples/client-examples/pom.xml
- opc-ua-sdk/sdk-client/pom.xml
- opc-ua-sdk/sdk-core/pom.xml
- opc-ua-sdk/sdk-server/pom.xml
- opc-ua-stack/bsd-parser/bsd-parser-core/pom.xml
- opc-ua-stack/bsd-parser/bsd-parser-gson/pom.xml
- opc-ua-stack/stack-client/pom.xml
- opc-ua-stack/stack-core/pom.xml
- opc-ua-stack/stack-server/pom.xml
- pom.xml
> Add automatic module names (#584)

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/util/HostnameUtil.java
Prevents unnecessary call to isLoopbackAddress() when includeLoopback
parameter is true because it can be a slow operation on some systems.
fixes #641
> Short-circuit call to InetAddress.isLoopbackAddress()

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/identity/X509IdentityProvider.java
Fixes two issues with X509IdentityProvider when using SecurityPolicy.None
1. the server certificate bytes are not used even though there might be one in the endpoint
2. the wrong securityPolicyUri is used when building the SignatureData
fixes #647
> Fix X509IdentityProvider when using SecurityPolicy.None

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/identity/X509IdentityProvider.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/SessionFsmFactory.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/SessionManager.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/AbstractX509IdentityValidator.java
Additionally, when verifying a SignatureData in the server, first verify using
the leaf certificate and then fall back to using the full certificate chain if
that fails.
fixes #658
> Create SignatureData in the client using the server's leaf certificate

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/SessionManager.java
Additionally, strip the non-essential fields from the EndpointDescription
and ApplicationDescription structures returned by CreateSession as recommended
by the spec.
fixes #661
> Filter endpoints in CreateSession the same way as GetEndpoints

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/AddressSpaceComposite.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/ManagedNamespace.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/SimpleAddressSpaceFilter.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/subscriptions/SubscriptionManager.java
This fix has two parts. First, simply allow Bad_NodeIdUnknown when trying to
read the MinimumSamplingInterval attribute during a ModifyMonitoredItems service
call. Second, Modify SimpleAddressSpaceFilter to filter MonitoredItem service calls
with a different predicate than the other services. This will allow AddressSpace
implementations to test whether the service call should be handled based on some
other criteria than the Node simply existing in its NodeManager.
fixes #547
> Allow monitored item modification for Nodes that no longer exist

- opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/security/DefaultClientCertificateValidator.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/validation/ValidationCheck.java
- opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/security/DefaultServerCertificateValidator.java
Allow suppressing the check that a remote application's end-entity certificate has a
SubjectAlternativeName URI that matches the application URI in its ApplicationDescription.
This check is not technically optional or suppressible according to the spec, but because
Java's certificate parsing routine turns invalid URIs into a null/empty String this check
fails more often than it should, since many applications will use whitespace in their URI
without properly URL-encoding it.
fixes #672
> Allow application URI security check to be suppressed

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/OpcUaClient.java
When OpcUaClient reads and updates the namespace table it clears it before updating with the new one read from the server. If the server returned an empty array then the client namespace table will now be empty.
Even though this is defective behavior on the server's part we can still ensure the client's namespace table at least has the OPC UA namespace URI at index 0.
fixes #681
> Ensure OPC UA namespace URI is always present at index 0

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/AddressSpace.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/BrowseHelper.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/nodes/UaObjectNode.java
The spec says this should be an empty array when there are no references
but it has been observed that some out-of-spec servers will send a null
value instead.
fixes #692
> Guard against BrowseResult#getReferences() returning null

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/SessionFsmFactory.java
This prevents the FSM from getting stuck in a reconnect "loop" when a
defective server doesn't respond with one of the expected StatusCodes or
doesn't respond with a ServiceFault at all, e.g. responding instead with
a channel layer Error message instead.
The main consequence of this is that subscription transfer will only be
attempted once after re-establishing a session, leaving a small possibility
that some legitimate type of failure, such as a connection interruption,
occurring as the subscriptions are being transferred results in the
subscriptions being subsequently re-created when it may have been possible
to transfer them.
fixes #722
> Notify subscription transfer failed after *any* failure

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/AbstractX509IdentityValidator.java
When SecurityPolicy.None is being used the certificate bytes from SecurityConfiguration will be
empty, causing the signature validation to fail because the client will have constructed the data
using the certificate bytes from the EndpointDescription.
fixes #770
> Get certificate bytes from endpoint when constructing signature data

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/SessionFsmFactory.java
Because handleFailureToOpenSession was not called inside an FSM action it was possible for a
GetSession Event to be processed right after the SessionFuture had been removed, leading to NPE
when accessing the inner CompletableFuture field.
fixes #776
> Fix possible NPE in Session FSM

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscriptionManager.java
This function doesn't exist on Android (yet) and there is an easy enough
alternative implementation of getLifetimeCount.
fixes #779
> Avoid the use of BigInteger::longValueExact

- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/Variant.java
- opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/types/builtin/VariantTest.java
OPC UA 1.04 further clarifies that it is legal to construct a Variant
containing a DataValue for use in e.g. method arguments or PubSub but it is
not legal for a DataValue to contain such a Variant. Without knowledge of
where the Variant will be used it does not make sense to restrict construction
of such a Variant.
fixes #805
> Remove check preventing Variant construction with DataValue

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/SessionFsmFactory.java
- opc-ua-stack/stack-client/pom.xml
Ensure that handleFailureToOpenSession is the first transition action
to run when transitioning to CreatingWait state.
fixes #807
> Fix NPEs on transition to CreatingWait state

- opc-ua-sdk/dictionary-reader/src/main/java/org/eclipse/milo/opcua/sdk/client/dtd/DataTypeDictionaryReader.java
- opc-ua-sdk/dictionary-reader/src/main/resources/Opc.Ua.Types.bsd
- opc-ua-sdk/dictionary-reader/src/test/java/org/eclipse/milo/opcua/sdk/client/dtd/DataTypeDictionaryReaderTest.java
The binary DataType Dictionary for the OPC UA namespace should be the
same in every server, so instead of reading it from the server we can
read an embedded copy from the filesystem before further processing it.
fixes #808
> Read OPC UA binary DataType Dictionary from disk instead of from server

- opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/AddressSpaceTest.java
- opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/methods/UaMethodTest.java
- opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/test/TestNamespace.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/nodes/UaMethodNode.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/nodes/UaObjectNode.java
MethodNodes are allowed to omit the InputArguments and OutputArguments
PropertyNodes all together rather than using Nodes with empty values.
fixes #815
> Fix Bad_NotFound calling methods with no InputArguments or OutputArguments

- milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/ClientExample.java
- milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/ClientExampleRunner.java
- milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/KeyStoreLoader.java
- milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleServer.java
- milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/KeyStoreLoader.java
Demonstrate and enable by default secure connections and certificate validation against the trust list in the client examples.
> Enable security by default in the client examples

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/subscriptions/SubscriptionManager.java
When the Session is closed and the delete subscriptions flag is set de-queue
any remaining PublishRequests and return a ServiceFault with Bad_SessionClosed.
fixes #846
> Return Bad_SessionClosed for remaining PublishRequests

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/subscriptions/UaSubscription.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/ManagedSubscription.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscriptionManager.java
Use new callbacks from UaSubscription.NotificationListener to ensure we
receive notification that data was lost or a subscription transfer failed.
fixes #865
> Fix missing callback invocations in ManagedSubscription.StatusListener 

- opc-ua-stack/bsd-core/pom.xml
- opc-ua-stack/bsd-parser/pom.xml
- opc-ua-stack/stack-core/pom.xml
This should fix an error using DataTypeDictionaryGenerator on JDK 17.
fixes #962
> Update jaxb-runtime and jakarta.activation dependencies

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/SessionFsmFactory.java
> Use configured session locale ids when activating a session

- milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/ReadWriteCustomDataTypeNodeExample.java
- milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleNamespace.java
- milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/types/CustomStructType.java
- opc-ua-sdk/dictionary-manager/src/main/java/org/eclipse/milo/opcua/sdk/server/dtd/DataTypeDictionaryManager.java
- opc-ua-stack/bsd-generator/src/main/java/org/eclipse/milo/opcua/binaryschema/generator/DataTypeDictionaryGenerator.java
When generating the BSD XML for a struct that has an enum type field
assume the namespace URI is that of the current dictionary. Enumerations
are not currently defined with enough extra information to look up the
namespace URI; consequently a struct definition may not reference an
enum type defined in another dictionary.
fixes #964
> Fix NPE generating struct with enum field

- opc-ua-stack/stack-client/pom.xml
This version does not include an unintentional dependency on Kotlin.
fixes #972
> Update netty-channel-fsm to version 0.7

- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/ExpandedNodeId.java
- opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/types/builtin/ExpandedNodeIdTest.java
- opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/types/builtin/NodeIdTest.java
This new implementation also fixes a bug when parsing a String identifier that
contains additional semicolons.
fixes #976
> Implement ExpandedNodeId.parse without NodeId.parse

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/namespaces/OpcUaNamespace.java
In the ResendData Method implementation, only return Bad_SubscriptionIdInvalid when the subscription doesn't exist at all.
fixes #984
> Return Bad_UserAccessDenied if subscription belongs to another session

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/ManagedAddressSpace.java
The StatusCode returned when the Object exists but the Method does not is
supposed to be the more specific Bad_MethodInvalid instead of Bad_NodeIdUnknown.
fixes #982
> Use different StatusCodes for Object not found vs Method not found

- opc-ua-sdk/dictionary-reader/pom.xml
- opc-ua-stack/stack-client/pom.xml
This version does not include an unintentional dependency on Kotlin.
fixes #972
> Update netty-channel-fsm to version 0.8

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/OpcUaServer.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/DefaultViewServiceSet.java
The CTT requires browsing fail at the service level if the requested
View is not known to the server.
fixes #981
> Check that Views are registered before continuing Browse service

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/helpers/BrowseHelper.java
Don't apply the result mask immediately, because the NodeClass is
needed further in the browse logic, regardless of whether it's
eventually returned as part of the ReferenceDescription or not.
fixes #997
> Apply BrowseResultMask later, when building ReferenceDescriptions

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/Event.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/SessionFsmFactory.java
- opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/UaStackClient.java
- opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/transport/tcp/OpcTcpTransport.java
If the transport allows it, listen for connection loss and immediately 
transition to the `CreatingWait` state when it happens. This will speed up 
recovery of the session and reduce the chance requests are sent using the old 
Session, before a new one is activated, when the underlying connection is 
re-established.
fixes #1011
> Transition to CreatingWait state when connection is lost

- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/SelfSignedCertificateGenerator.java
This allows some amount of compatibility with OPC UA 1.05, where it is preferred to have cA=false instead, but there is a backwards-compatibility concession that allows cA=true if `pathLenConstraint` is present and set to 0.
fixes #1110
> Generate self-signed certs with pathLenConstraint=0

- opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/services/ServiceRequest.java
- opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/transport/uasc/UascServerSymmetricHandler.java
The full certificate chain is required, if provided by the client, when comparing the certificate bytes provided during session creation.
fixes #1119
> Provide full certificate chain bytes in ServiceRequest

- opc-ua-stack/pom.xml
- opc-ua-stack/stack-core/pom.xml
This also changes the dependencies from the `-jdk15on` to the `-jdk18on` variations.
fixes #1133
> Update Bouncy Castle libraries to 1.75

- milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleNamespace.java
- milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/RestrictedAccessFilter.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/OpcUaServerConfigBuilder.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/Session.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/SessionManager.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/AbstractIdentity.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/AbstractIdentityValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/AbstractUsernameIdentityValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/AbstractX509IdentityValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/AnonymousIdentityValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/CompositeValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/DefaultAnonymousIdentity.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/DefaultIssuedIdentity.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/DefaultUsernameIdentity.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/DefaultX509UserIdentity.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/Identity.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/IdentityValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/UsernameIdentityValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/X509IdentityValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/servicesets/impl/DefaultSubscriptionServiceSet.java
Clean up `IdentityValidator` by removing the unnecessary type parameter and introduce the `Identity` interface to use as the return type.
> Refactor `IdentityValidator` and introduce `Identity`

- milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/AttributeLoggingFilter.java
- milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/RestrictedAccessFilter.java
- opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/UaVariableNodeTest.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/AttributeReader.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/AttributeWriter.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/ManagedAddressSpace.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/diagnostics/variables/Util.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/DefaultAttributeFilter.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/UaNode.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/UaServerNode.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/filters/AttributeFilter.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/filters/AttributeFilterChain.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/filters/AttributeFilterContext.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/filters/AttributeFilters.java
- opc-ua-sdk/sdk-server/src/test/java/org/eclipse/milo/opcua/sdk/server/util/AttributeWriterTest.java
These are now called by AttributeReader and AttributeWriter when responding to Read and Write service calls, and allow for filter implementations that can indicate a failure to get or set an attribute by throwing UaException, as opposed to the `getAttribute` and `setAttribute` methods that must not throw.
Additionally, filter contexts are simplified, removing the separate GetAttributeContext and SetAttributeContext in favor of just AttributeFilterContext.
> Add AttributeFilter `::readAttribute` and `::writeAttribute`

- pom.xml
Mark imported packages sun.security.* as optional when generating manifest.
Fixes https://github.com/eclipse/milo/issues/1174
Before you submit a pull request please acknowledge the following:
See [CONTRIBUTING](https://github.com/eclipse/milo/blob/master/CONTRIBUTING.md) for more information.
> Missing Constraint when using as bundle in OSGi context #1174

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/SessionFsmFactory.java
> Force TCP reconnect when session keep-alive failure occurs

- opc-ua-stack/pom.xml
This PR contains only the update of the guava version. It should make the warning about insecure transitive dependencies disappear, even though milo is basically unaffected.
Before you submit a pull request please acknowledge the following:
See [CONTRIBUTING](https://github.com/eclipse/milo/blob/master/CONTRIBUTING.md) for more information.
> Updated Guava version to 32.1.3-jre

- milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/MethodExample2.java
- opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/typetree/DataTypeTreeBuilderTest.java
- opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/core/DataTypeTreeTest.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/typetree/DataTypeTreeBuilder.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/Tree.java
Implements recursive browsing of the DataType hierarchy in an efficient manner without sending out an increasing amount of parallel browse requests as it descends.
While the previous naive strategy worked well enough against most servers, it often caused `Bad_OutOfMemory` conditions in servers built on embedded SDKs.
> New implementation of DataTypeTreeBuilder

- opc-ua-stack/transport/src/main/java/org/eclipse/milo/opcua/stack/transport/server/uasc/UascServerAsymmetricHandler.java
This allows the configuration and matching of endpoints that are otherwise identical except their certificates. This can be useful in scenarios where existing trust relationships are maintained while new certificates are introduced.
fixes #1230
> Use thumbprint as additional criteria when matching endpoints

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/OpcUaClient.java
- opc-ua-stack/transport/src/main/java/org/eclipse/milo/opcua/stack/transport/client/OpcClientTransportConfig.java
- opc-ua-stack/transport/src/main/java/org/eclipse/milo/opcua/stack/transport/client/tcp/OpcTcpClientTransport.java
- opc-ua-stack/transport/src/main/java/org/eclipse/milo/opcua/stack/transport/client/tcp/OpcTcpClientTransportConfigBuilder.java
This allows e.g. a SOCKS proxy to be configured fairly easily: 
```java
public static void main(String[] args) throws UaException {
var client = OpcUaClient.create(
"opc.tcp://milo.digitalpetri.com:62541/milo",
endpoints -> endpoints.stream()
.filter(e -> Objects.equals(e.getSecurityPolicyUri(), SecurityPolicy.None.getUri()))
.findFirst(),
tcb -> tcb.setChannelPipelineCustomizer(p -> addSocksProxyHandler(p)),
ccb -> {}
);
client.connect();
}
private static void addSocksProxyHandler(ChannelPipeline pipeline) {
var handler = new Socks5ProxyHandler(new InetSocketAddress("localhost", 1080));
pipeline.addFirst(handler);
}
```
> Allow customization of Netty Bootstrap and ChannelPipeline

- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/SelfSignedCertificateGenerator.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/validation/CertificateValidationUtil.java
- opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/util/validation/CertificateValidationUtilTest.java
- generate new certificates without `cA` bit set
- generate new certificates without `keyAgreement` KeyUsage
- allow self-signed certificates without `cA` bit set to validate
fixes #1286
> Update certificate generation and validation logic

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/subscriptions/Subscription.java
Errata 1.04.8 changed Subscription State Table row 9 so that the keep alive counter is decremented upon the initial transition. This results in a keep alive PublishResponse being sent one publishing interval earlier, which better matches the description of the behavior in the spec.
fixes #1304
> Decrement `keepAliveCounter` on transition to `State.KeepAlive`

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/servicesets/impl/helpers/BrowsePathsHelper.java
When processing browse paths return `Bad_NodeIdUnknown` instead of `Bad_NoMatch` if the browse result was `ReferenceResult.BadNodeIdUnknown`.
fixes #1315
> Return Bad_NodeIdUnknown for ReferenceResult.BadNodeIdUnknown

- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/validation/CertificateValidationUtil.java
- opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/util/validation/CertificateValidationUtilTest.java
Implements case-insensitive hostname comparison to follow the [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-6.2.2.1). A similar discussion can be found [here](https://opcfoundation.org/forum/opc-ua-standard/case-sensitivity-of-opc-ua-opc-tcp-endpoints/).
When trying to use the Eclipse Milo client to connect to a server that has a certificate with an uppercase DNS name in its SAN section, the library raises the following error when validating the DNS name against the hostname (lowercase) extracted from the connection endpoint.
```
INFO | jvm 1 | 2024/09/19 18:07:51 | java.util.concurrent.CompletionException: UaException: status=Bad_CertificateHostNameInvalid, message=The HostName used to connect to a Server does not match a HostName in the Certificate.
INFO | jvm 1 | …
```
> Use case insensitive hostname comparison for validating certificate

- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/channel/ChunkDecoder.java
- opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/channel/ChunkDecoderTest.java
> Allow sequenceNumber to wrap from UInt32.MAX to 0

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/SessionFsmFactory.java
This avoids deadlock when the user makes a blocking call that requires the Session from the SessionFsm from inside the callback.
fixes #1300
> Notify SessionActivityListeners using client executor

- milo-examples/pom.xml
- opc-ua-sdk/dtd-core/pom.xml
- opc-ua-sdk/integration-tests/pom.xml
- opc-ua-sdk/pom.xml
- opc-ua-sdk/sdk-tests/pom.xml
- opc-ua-stack/guava-dependencies/pom.xml
- opc-ua-stack/pom.xml
- opc-ua-stack/stack-core/pom.xml
- pom.xml
Additionally, configure `versions-maven-plugin` to ignore pre-release versions and explicitly specify all plugin versions in the root `pom.xml`.
> Update Maven plugin versions

- milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleNamespace.java
- opc-ua-sdk/dtd-manager/src/main/java/org/eclipse/milo/opcua/sdk/server/dtd/BinaryDataTypeDictionaryManager.java
- opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/test/TestNamespace.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/AttributeReader.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/OpcUaServer.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/SessionManager.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/diagnostics/variables/ServerDiagnosticsSummaryVariable.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/diagnostics/variables/SessionDiagnosticsVariable.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/diagnostics/variables/SessionDiagnosticsVariableArray.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/diagnostics/variables/SessionSecurityDiagnosticsVariable.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/diagnostics/variables/SessionSecurityDiagnosticsVariableArray.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/diagnostics/variables/SubscriptionDiagnosticsVariable.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/diagnostics/variables/SubscriptionDiagnosticsVariableArray.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/events/EventContentFilter.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/items/MonitoredEventItem.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/methods/AbstractMethodInvocationHandler.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/namespaces/OpcUaNamespace.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/servicesets/impl/DefaultAttributeServiceSet.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/subscriptions/Subscription.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/subscriptions/SubscriptionManager.java
- opc-ua-sdk/sdk-server/src/test/java/org/eclipse/milo/opcua/sdk/server/nodes/UaNodeTest.java
- opc-ua-sdk/sdk-server/src/test/java/org/eclipse/milo/opcua/sdk/server/nodes/factories/NodeFactoryTest.java
Adds separate "dynamic" `DataTypeManager` and `EncodingContext` to `OpcUaServer` and updates the example namespace/server to register a type at runtime and expose it.
fixes #1371
> Support runtime/dynamic DataTypes in Server

- milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleServer.java
- opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/test/TestServer.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/AbstractIdentityValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/AbstractUsernameIdentityValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/AbstractX509IdentityValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/AnonymousIdentityValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/CompositeValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/IdentityValidator.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/identity/UsernameIdentityValidator.java
Use this new method in `CompositeValidator` to only attempt validation with validators that support the incoming token type.
Additionally, remove the combined anonymous identity support from `UsernameIdentityValidator` and `AbstractUsernameIdentityValidator`.
Update ExampleServer to use `CompositeValidator` so it continues to support anonymous identities.
fixes #1382
> Add `IdentityValidator::getSupportedTokenTypes`

- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/Matrix.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/Variant.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/ArrayUtil.java
- opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/types/builtin/MatrixTest.java
- opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/types/builtin/VariantTest.java
Improves usability of `equals` in Variant and Matrix by supporting equality between contained values that are primitive in one and boxed in the other, but otherwise equal. 
fixes #1384
> Support mixed primitive/boxed equality in Variant and Matrix

- milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/WriteExample.java
- opc-ua-stack/encoding-json/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/json/OpcUaJsonEncoderTest.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/binary/OpcUaBinaryEncoder.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/DataValue.java
- opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/binary/OpcUaBinaryEncoderTest.java
A `null` value is semantically the same, and encodes the same, as `StatusCodes.GOOD`. Any distinction is lost during serialization.
> Disallow `null` for StatusCode field in DataValue

- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/NamespaceTable.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/ServerTable.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/UriArray.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/binary/OpcUaBinaryEncoder.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/ExpandedNodeId.java
- opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/UriArrayTest.java
Namespace URIs are indexed using UInt16 but server URIs are indexed using UInt32. Modify UriArray to handle different index types and then use the appropriate index type in NamespaceTable and ServerTable.
> Use UInteger for the index type of ServerTable

- opc-ua-stack/encoding-json/pom.xml
- opc-ua-stack/encoding-json/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/json/OpcUaJsonDecoder.java
- opc-ua-stack/encoding-json/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/json/OpcUaJsonEncoder.java
- opc-ua-stack/encoding-json/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/json/OpcUaJsonDecoderTest.java
- opc-ua-stack/encoding-json/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/json/OpcUaJsonEncoderTest.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/ExpandedNodeId.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/NodeId.java
The JSON encoding defined in part 6 has been modified after feedback from SDK vendors since `OpcUaJsonEncoder` and `OpcUaJsonDecoder` were implemented. 
Instead of "reversible" and "non-reversible" encodings there is now "verbose" and "compact". Where applicable, the "verbose" encoding eschews numeric references for which the receiving application might not have context and includes symbolic names and URIs when possible.
The types for which the encoding has changed include:
- NodeId
- ExpandedNodeId
- QualifiedName
- StatusCode
- Matrix (multi-dimension array) 
- LocalizedText (always encoded as JSON object)
- ExtensionObject (always encoded as JSON object)
- Variant (always "verbose")
> Update JSON encoding for latest OPC UA 1.05 Part 6 draft

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/PublishingManager.java
Set `lastSequenceNumber` even if the first PublishResponse is empty (keep-alive). 
This prevents an unnecessary Republish call when a Server sends an empty (keep-alive) first PublishResponse followed by a second PublishResponse once it has acquired initial values for the MonitoredItems in the Subscription. This is explicitly allowed by the specification.
> Set `lastSequenceNumber` on the first PublishResponse

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/Event.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/SessionFsmFactory.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/State.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/PublishingManager.java
Modifies the Session FSM so that upon reconnecting after having been in the "Active" state, it first attempts to reactivate the existing Session.
This behavior has always been called for by OPC UA Part 4 (see https://reference.opcfoundation.org/Core/Part4/v105/docs/6.7) but was never implemented.
> Implement Session reactivation in Session FSM

- milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/ReadWriteCustomDataTypeNodeExample.java
- milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/UnifiedAutomationReadCustomDataTypeExample1.java
- milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/UnifiedAutomationReadCustomDataTypeExample2.java
- milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/UnifiedAutomationReadCustomDataTypeExampleLegacy.java
- milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleNamespace.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/subscriptions/Subscription.java
- opc-ua-stack/encoding-json/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/json/OpcUaDefaultJsonEncoding.java
- opc-ua-stack/encoding-json/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/json/OpcUaDefaultJsonEncodingTest.java
- opc-ua-stack/encoding-xml/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/xml/OpcUaDefaultXmlEncoding.java
- opc-ua-stack/encoding-xml/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/xml/OpcUaXmlEncoder.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/OpcUaDefaultXmlEncodingTest.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/args/ArrayArguments.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/args/MatrixArguments.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/args/ScalarArguments.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/args/VariantArguments.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/binary/OpcUaDefaultBinaryEncoding.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/DataTypeEncoding.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/ExtensionObject.java
- opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/binary/OpcUaDefaultBinaryEncodingTest.java
The encode/decode methods on `DataTypeEncoding` and `ExtensionObject` no longer need to supply encoding/type NodeIds because they are implicitly available from either the `UaStructureType` being encoded or the `ExtensionObject` being decoded.
> Remove superfluous encoding ids from method interfaces

- opc-ua-sdk/codec-json/src/main/java/org/eclipse/milo/sdk/core/types/json/JsonStruct.java
- opc-ua-sdk/dtd-core/src/main/java/org/eclipse/milo/opcua/sdk/core/dtd/BsdStructWrapper.java
- opc-ua-sdk/sdk-core/src/main/java/org/eclipse/milo/opcua/sdk/core/types/DynamicType.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/namespaces/loader/DataTypeNodeLoader.java
- opc-ua-stack/encoding-xml/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/xml/OpcUaDefaultXmlEncoding.java
- opc-ua-stack/encoding-xml/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/xml/OpcUaXmlEncoder.java
- opc-ua-stack/encoding-xml/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/xml/XmlSerializationUtil.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/OpcUaDefaultXmlEncodingTest.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/OpcUaXmlEncoderTest.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/XmlSerializationUtilTest.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/args/ArrayArguments.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/args/MatrixArguments.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/args/ScalarArguments.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/args/StructArguments.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/args/VariantArguments.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/UaDataType.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/structured/ThreeDCartesianCoordinates.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/structured/ThreeDFrame.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/structured/ThreeDOrientation.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/structured/ThreeDVector.java
Rename `getEncodingName()` to `getTypeName()`.
Don't generate constructors using the SymbolicName as the BrowseName.
The "ThreeD" structures need to implement `getTypeName()` because their actual names begin with "3D" - "ThreeD" is just the SymbolicName.
With `getTypeName()` being implemented where required, the XML name encoding rules defined in https://reference.opcfoundation.org/Core/Part6/v105/docs/5.1.13 can be applied during XML encoding.
Some structure and enum elements were missing the namespace prefix. OPC UA (ns0) types get special treatment re: namespaces and XML name encoding rules.
> DataType and XML Encoding Corner Cases

- opc-ua-stack/encoding-xml/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/xml/OpcUaDefaultXmlEncoding.java
- opc-ua-stack/encoding-xml/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/xml/OpcUaXmlEncoder.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/OpcUaXmlEncoderArrayTest.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/OpcUaXmlEncoderMatrixTest.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/OpcUaXmlEncoderScalarTest.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/OpcUaXmlEncoderTest.java
Additional changes:
- add constructor and `reset` method that accept `Writer`
- add `getOutput` and `getOutputString` methods
- try-with-resources for all usages of OpcUaXmlEncoder
> Implement Autocloseable in OpcUaXmlEncoder

- pom.xml
Runs with `mvn verify`, but only with `-Peclipse-license-check`.
> Configure `license-tool-plugin` behind a profile

- opc-ua-stack/encoding-xml/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/xml/OpcUaXmlDecoder.java
- opc-ua-stack/encoding-xml/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/xml/OpcUaXmlEncoder.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/OpcUaXmlEncoderTest.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/OpcUaXmlSerializationTest.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/args/ArrayArguments.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/args/MatrixArguments.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/args/ScalarArguments.java
- opc-ua-stack/encoding-xml/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/xml/args/VariantArguments.java
* add special handling for null Variant serialization in XML encoder
* add test case to `OpcUaXmlEncoderTest` specifically for null Variants
* update argument providers with correct null representation
* add comprehensive `OpcUaXmlSerializationTest` for round-trip coverage
> Fix XML serialization of "null" Variant

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/diagnostics/objects/SessionsDiagnosticsSummaryObject.java
Because the `SessionDiagnosticObject` was added to the `sessionDiagnosticsObjects` map before having `startup()` called, it was possible that during shutdown we could attempt to shut down a `SessionDiagnosticObject` that hadn't been started yet, and therefore had `null` fields.
fixes #1445
> Fix NPE in `SessionDiagnosticsObject::onShutdown`

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscription.java
Check if `serverState` is `null` before attempting to create MonitoredItems, which is possible if the user has not yet created the Subscription, or if they had created it, but it was reset because, e.g., Subscription transfer failed.
fixes #1446
> Fix NPE in `OpcUaSubscription::createMonitoredItems`

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/OpcUaServer.java
This will disconnect clients before shutting down namespaces, which should help with some of the race conditions in the diagnostic nodes when sessions are being created as the nodes are shutting down.
> Unbind transports first in `OpcUaServer::shutdown`

- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/binary/OpcUaBinaryEncoder.java
- opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/binary/ExpandedNodeIdSerializationTest.java
Using the namespace index is more compact than encoding a namespace URI.
It's also a workaround for bugs observed in the CTT and UaExpert, where the Client ignores the explicitly specified namespace URI in the ExpandedNodeId and just uses the namespace index, which is always 0 when the URI is encoded.
fixes #1450
> Use namespace index if possible when encoding ExpandedNodeId

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/servicesets/impl/helpers/BrowseHelper.java
- opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/binary/OpcUaBinaryEncoder.java
- opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/binary/ExpandedNodeIdSerializationTest.java
If the server index indicates that the TargetNode is a remote Node, then the nodeId shall contain the absolute namespace URI. If the TargetNode is a local Node, the nodeId shall contain the namespace index.
See https://reference.opcfoundation.org/Core/Part4/v105/docs/7.30
fixes #1452
> Apply restrictions to ExpandedNodeId in ReferenceDescription 

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/servicesets/impl/helpers/BrowseHelper.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/servicesets/impl/helpers/BrowsePathsHelper.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/servicesets/impl/helpers/BrowseUtil.java
- opc-ua-sdk/sdk-server/src/test/java/org/eclipse/milo/opcua/sdk/server/servicesets/impl/helpers/BrowseUtilTest.java
- Introduce `BrowseUtil.normalize` to handle normalization of `ExpandedNodeId` values, ensuring they are relative for local nodes and absolute for non-local nodes.
- Replaced existing normalization logic across `BrowseHelper` and `BrowsePathsHelper` with calls to `BrowseUtil.normalize`.
fixes #1467
> "Normalize" ExpandedNodeId returned by browse services

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/UaVariableNode.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/UaVariableTypeNode.java
> Implement `UaVariableTypeNodeBuilder` for `UaVariableTypeNode`

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/OpcUaClient.java
Adds a new `OpcUaClient.create` overload that accepts an `OpcUaClientConfig` and a callback that can be used to configure an `OpcTcpClientTransportConfigBuilder`.
fixes #1486
> Add a new `OpcUaClient.create` overload

- opc-ua-sdk/sdk-core/src/main/java/org/eclipse/milo/opcua/sdk/core/NumericRange.java
- opc-ua-sdk/sdk-server/src/test/java/org/eclipse/milo/opcua/sdk/core/NumericRangeTest.java
Normally, when the lower bound of one of the index range parameters exceeds the length of the value it's being applied to, `Bad_IndexRangeNoData` is returned for the entire operation.
In the case of a String array or ByteString array, it has been decided that the intended behavior is to return a null or empty value instead of `Bad_IndexRangeNoData` for the entire operation.
e.g. given the value `["TestString", "Test", "String"]`, reading with index range `"0:2,7:9"` would yield `["ing", null, null]` rather than `Bad_IndexRangeNoData`.
fixes #1496
> Update index range behavior for `String` and `ByteString` arrays

- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/typetree/DataTypeTreeBuilder.java
Not sure how this ended up here, but it's a mistake.
> Remove `OpcUaClient::getOperationLimits()` call

- opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/OpcUaClientDeadlockTest.java
- opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/test/AbstractClientServerTest.java
- opc-ua-stack/transport/src/main/java/org/eclipse/milo/opcua/stack/transport/client/AbstractUascClientTransport.java
A deadlock could occur if a blocking client call was made from within the completion callback of an asynchronous client call.
The completion callbacks were being delivered using an ExecutionQueue, and a blocking call made from the callback would end up waiting for a response that needed to be delivered using the same queue.
fixes #1537
> Fix a deadlock in OpcUaClient async callbacks

- milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/ClientExampleRunner.java
- opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscriptionTest.java
- opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/test/AbstractClientServerTest.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscription.java
MonitoredItems aren't supposed to be added or removed before the Subscription has been created and moved out of `SyncState.INITIAL`. Currently, nothing prevents this, which results in the Subscription subsequently moving to `SyncState.UNSYNCHRONIZED` even though it doesn't exist yet, and then eventually the call to create fails with `Bad_InvalidState`.
This guards the add/remove MonitoredItem methods with checks that throw `UaRuntimeException` if they are called before the Subscription has been created. 
Ideally these would throw `UaException` instead but I'm trying to avoid modifying the API method signatures.
> Throw UaRuntimeException for add/remove on uninitialized Subscription

- opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/SessionValidationTest.java
- opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/test/AbstractClientServerTest.java
- opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/test/TestClient.java
- opc-ua-sdk/sdk-client/pom.xml
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/OpcUaClient.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/OpcUaClientConfig.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/OpcUaClientConfigBuilder.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/SessionFsmFactory.java
- opc-ua-sdk/sdk-client/src/test/java/org/eclipse/milo/opcua/sdk/client/session/SessionEndpointValidationTest.java
- opc-ua-sdk/sdk-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/OpcUaClientConfigTest.java
Adds optional validation of the endpoints returned by the CreateSession service against the endpoints returned by GetEndpoints service during discovery.
> Implement optional Session endpoint validation

- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/subscriptions/Subscription.java
Follows the established best practice of scheduling a task with the `ScheduledExecutorService` and then immediately offloading the potentially blocking action to the `ExecutorService` when it runs.
Turns out this is also important because a Thread's uncaught exception handler won't be executed for tasks scheduled with a `ScheduledExecutorService`.
> Run `onPublishingTimer` on the configured ExecutorService

- opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/SubscriptionTransferTest.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/servicesets/impl/DefaultSubscriptionServiceSet.java
Adds validation for `AnonymousIdentity` during subscription transfer.
- Ensure `MessageSecurityMode` is not `None`.
- Verify `ApplicationUri` matches between sessions.
fixes #1563
> Validate TransferSubscription for anonymous identities

- opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscriptionTest.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaMonitoredItem.java
- opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscription.java
- reset Subscription state when Bad_Timeout status is received the same way its reset when a transfer fails
- reset the state of each MonitoredItem when the Subscription state is reset
This allows the implementation of `SubscriptionListener::onStatusChanged` and `SubscriptionListener::onTransferFailed` to behave the same way when restoring a subscription: just call `create()` and then `synchronizeMonitoredItems()`.
> Reset OpcUaSubscription when Bad_Timeout is received

- opc-ua-sdk/sdk-core/src/main/java/org/eclipse/milo/opcua/sdk/core/WriteMask.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/AttributeWriter.java
- opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/servicesets/impl/DefaultAccessController.java
- opc-ua-sdk/sdk-server/src/test/java/org/eclipse/milo/opcua/sdk/server/servicesets/impl/DefaultAccessControllerTest.java
Moves UserWriteMask check from AttributeWriter to DefaultAccessController, where it will be applied to all incoming writes and not just those to UaNodes using AttributeWriter.
> Check UserWriteMask in DefaultAccessController
