eclipse-milo/milo

opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/subscriptions/UaSubscription.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscription.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscriptionManager.java
opc-ua-sdk/sdk-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/OpcUaClientIT.java

The current API requires MonitoringMode.Sampling be used when creating items in order to allow callers a chance to set consumers and do other bookkeeping before values arrive, and then MonitoringMode.Reporting to be set once ready.
The new method allows callers to provide a callback that will be run with a guarantee that it happens before values can arrive.

Fix a race condition when creating monitoring items.

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/unsigned/newtypes/OutOfRangeException.java
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/unsigned/newtypes/UByte.java
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/unsigned/newtypes/UInt32.java
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/unsigned/newtypes/UInt64.java
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/unsigned/newtypes/UInt8.java
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/unsigned/newtypes/UnsignedArithmethic.java
opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/types/builtin/unsigned/newtypes/AbstractUnsingedTest.java
opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/types/builtin/unsigned/newtypes/UInt8Test.java

I did things a bit differently than you ;-) So let's discuss it.
But I also added a unit test.
Signed-off-by: Jens Reimann <jreimann@redhat.com>

Implement UInt8 type and add test case

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/serialization/xml/XmlDecoder.java
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/serialization/xml/XmlEncoder.java
opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/serialization/xml/XmlDecoderTest.java
opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/serialization/xml/XmlEncoderTest.java

add implementation for decodeExpandedNodeId and fix decodeLocalizedText error on empty

Implementation for XmlDecoder/XmlEncoder

---

pom.xml

Adds additional dependencies to checkstyle plugin as Jens suggested.

[#86] fix whatever is preventing Hudson from building

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/namespaces/VendorNamespace.java

This change differs between plain java, JMX and com.sun JMX in a way
that com.sun JMX is optional and will not fail.
When running inside OSGi it may be that "com.sun" is not available and
thus may fail with a NoClassDefFoundException.
Signed-off-by: Jens Reimann <jreimann@redhat.com>

Make com.sun JMX handling optional

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/NodeId.java

This change adds two mixed (uint/int) constructors

Add mixed int/uint constructors

---

opc-ua-sdk/pom.xml
opc-ua-stack/pom.xml

version is already declared in parent pom

Avoid duplication of Maven plugin version declaration

---

opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/handlers/UaTcpClientMessageHandler.java

Reset secure channel when server closes the connection unexpectedly

---

opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/ClientChannelManager.java
opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/UaTcpStackClient.java
opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/handlers/UaTcpClientMessageHandler.java

This behavior was either not implemented in most stacks, or was
implemented incorrectly, and is being removed in OPC UA 1.04.

Don't attempt to resume the previous secure channel after reconnecting

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/DataValue.java

[#200] fix CTT Attribute Read 006

---

opc-ua-sdk/sdk-core/src/main/java/org/eclipse/milo/opcua/sdk/core/NumericRange.java

[#204] Fixes CTT Attribute Read Err-015

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/items/MonitoredDataItem.java

[#141] Fixes CTT Monitor Items Deadband Filter Err-006

---

milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleNamespace.java
opc-ua-sdk/sdk-core/src/main/java/org/eclipse/milo/opcua/sdk/core/AccessLevel.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/util/AttributeReader.java

[#236] Fixes CTT Attribute Read err-016

---

milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleNamespace.java

[#234] Fixes CTT Attribute Read 025

---

milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleNamespace.java

[#232] Fixes CTT Attribute Read 023

---

opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/OpcUaClient.java

Ignore null and duplicate URIs when reading NamespaceArray

---

opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/config/OpcUaClientConfigBuilder.java
opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/config/UaTcpStackClientConfig.java
opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/config/UaTcpStackClientConfigBuilder.java
opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/handlers/UaTcpClientAcknowledgeHandler.java
opc-ua-stack/stack-tests/src/test/java/org/eclipse/milo/opcua/stack/client/config/UaTcpStackClientConfigTest.java

Make time to wait for Acknowledge configurable

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/channel/ChunkDecoder.java

Check refCnt() before releasing buffers after a decoding error

---

opc-ua-stack/pom.xml

Upgrade Netty to 4.1.30.Final

---

milo-examples/client-examples/pom.xml
milo-examples/server-examples/pom.xml
milo-examples/standalone-examples/pom.xml
opc-ua-sdk/pom.xml
opc-ua-sdk/sdk-tests/pom.xml
opc-ua-stack/pom.xml
opc-ua-stack/stack-core/pom.xml
opc-ua-stack/stack-server/pom.xml
opc-ua-stack/stack-tests/pom.xml

Upgrade Bouncy Castle to 1.60

---

opc-ua-sdk/pom.xml
opc-ua-sdk/sdk-server/pom.xml
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/DefaultAttributeHistoryServiceSet.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/DefaultAttributeServiceSet.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/DefaultMethodServiceSet.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/DefaultMonitoredItemServiceSet.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/DefaultNodeManagementServiceSet.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/DefaultQueryServiceSet.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/DefaultViewServiceSet.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/ServiceCounter.java

Remove dependency on metrics library

---

opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/identity/AnonymousProvider.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/identity/CompositeProvider.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/identity/IdentityProvider.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/identity/SignedIdentityToken.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/identity/UsernameProvider.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/identity/X509IdentityProvider.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/subscriptions/UaSubscription.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/methods/GetMonitoredItems.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/states/AbstractSessionState.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscriptionManager.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/events/EventContentFilter.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/delegates/AttributeDelegateChain.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/factories/NodeFactory.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/factories/ReferenceTable.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/helpers/BrowseHelper.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/subscriptions/SubscriptionManager.java
opc-ua-sdk/sdk-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/api/identity/AnonymousProviderTest.java
opc-ua-stack/pom.xml
opc-ua-stack/stack-core/pom.xml

Remove dependency on jool

---

opc-ua-stack/pom.xml

Update Netty to 4.0.56.Final

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/unsigned/UInteger.java

Signed-off-by: Ahmed Ashour <asashour@yahoo.com>

Correct JavaDoc about not deprecated method

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/application/CertificateValidator.java
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/application/DefaultCertificateValidator.java
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/PShaUtil.java

Similar to #381, but for `0.3`
Signed-off-by: Ahmed Ashour <asashour@yahoo.com>

Fix eclipse checkstyle warnings

---

milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/ClientExampleRunner.java
milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/KeyStoreLoader.java

Path is the preferred way instead of File. Also, the created Input/OutputStreams should be gracefully closed.

Use Path instead of File

---

opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/UaTcpStackClient.java

Call connect() on the client instance before sending FindServersRequest

---

opc-ua-sdk/sdk-core/src/main/java/org/eclipse/milo/opcua/sdk/core/model/Property.java
opc-ua-sdk/sdk-core/src/main/java/org/eclipse/milo/opcua/sdk/core/model/QualifiedProperty.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/UaNode.java

Configure ArrayDimensions on Nodes created while setting a Property

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/config/OpcUaServerConfigLimits.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/subscriptions/Subscription.java

Allow min/max/default publishing interval to be configured

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/util/AnnotationBasedInvocationHandler.java

Add error logging to AnnotationBasedInvocationHandler

---

pom.xml

Add Automatic-Module-Name entry to JAR manifests

---

opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/transport/ServerChannelManager.java

Add a successfully bound bindAddress to the addresses Multiset

---

opc-ua-stack/bsd-parser/bsd-parser-core/src/main/java/org/eclipse/milo/opcua/binaryschema/AbstractCodec.java
opc-ua-stack/bsd-parser/bsd-parser-core/src/test/java/org/eclipse/milo/opcua/binaryschema/GenericBsdParserTest.java
opc-ua-stack/bsd-parser/bsd-parser-gson/src/test/java/org/eclipse/milo/opcua/binaryschema/gson/JsonBsdParserTest.java

Don't include length field in dynamic struct representations

---

opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/types/builtin/ByteStringTest.java
opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/types/structured/ApplicationDescriptionTest.java
opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/UaStackServer.java

Return distinct endpoints/urls in discovery services

---

opc-ua-stack/stack-client/pom.xml

This version makes all action callbacks asynchronously.
fixes #474

Upgrade netty-channel-fsm to version 0.3

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/AddressSpaceComposite.java

Complete BrowseContext exceptionally when the first browse fails

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/SessionManager.java

Treat null or empty UserIdentityToken as AnonymousIdentityToken

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/subscriptions/SubscriptionManager.java

Invoke MonitoredItem deletion callbacks when a Session is closed

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/NodeId.java
opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/types/builtin/NodeIdTest.java

Fix parsing of String-based NodeId containing a newline character

---

milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/TriggeringExample.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/subscriptions/UaSubscription.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscription.java

Implement addTriggeringLinks and removeTriggerLinks functions

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/subscriptions/SubscriptionManager.java

Pass current session to ReadContext used to read monitoring attributes

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/objects/AcknowledgeableConditionTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/objects/AlarmConditionTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/objects/ConditionTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/objects/DialogConditionTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/objects/ExclusiveLimitAlarmTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/objects/FiniteStateMachineTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/objects/NonExclusiveLimitAlarmTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/objects/ProgramStateMachineTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/objects/ProgramTransitionAuditEventTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/objects/ServerDiagnosticsTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/objects/ServerTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/objects/SessionDiagnosticsObjectTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/objects/SessionsDiagnosticsSummaryTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/objects/StateMachineTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/objects/TransitionEventTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/variables/BuildInfoTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/variables/SamplingIntervalDiagnosticsArrayTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/variables/SamplingIntervalDiagnosticsTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/variables/ServerDiagnosticsSummaryTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/variables/ServerStatusTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/variables/SessionDiagnosticsArrayTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/variables/SessionDiagnosticsVariableTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/variables/SessionSecurityDiagnosticsArrayTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/variables/SessionSecurityDiagnosticsTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/variables/SubscriptionDiagnosticsArrayTypeNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/model/nodes/variables/SubscriptionDiagnosticsTypeNode.java

Generate nodes with namespace URIs in component value getter/setters

---

opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/subscriptions/UaMonitoredItem.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaMonitoredItem.java

Pass SerializationContext to ValueConsumer and EventConsumer callbacks

---

opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/UaStackServer.java

Explicitly close connected channels during UaStackServer shutdown

---

opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/UaStackServer.java

Track EndpointConfigurations that successfully bound during startup

---

opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/DataTypeDictionaryReader.java

Log failures to read a DatatypeDictionary at WARN level

---

opc-ua-stack/bsd-parser/bsd-parser-core/src/test/java/org/eclipse/milo/opcua/binaryschema/BsdParserTest.java
opc-ua-stack/bsd-parser/bsd-parser-core/src/test/resources/dictionaries/BsdParserTest.bsd.xml
opc-ua-stack/bsd-parser/bsd-parser-gson/src/main/java/org/eclipse/milo/opcua/binaryschema/gson/JsonStructureCodec.java
opc-ua-stack/bsd-parser/bsd-parser-gson/src/test/java/org/eclipse/milo/opcua/binaryschema/gson/JsonBsdParserTest.java

Fix an issue encoding Bit from GSON LazilyParsedNumber

---

opc-ua-stack/bsd-parser/bsd-parser-core/src/main/java/org/eclipse/milo/opcua/binaryschema/AbstractCodec.java
opc-ua-stack/bsd-parser/bsd-parser-gson/src/main/java/org/eclipse/milo/opcua/binaryschema/gson/JsonStructureCodec.java

Handle negative array lengths while decoding

---

opc-ua-stack/pom.xml

Update Netty to version 4.1.45.Final

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/items/BaseMonitoredItem.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/items/MonitoredDataItem.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/items/MonitoredEventItem.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/subscriptions/SubscriptionManager.java

Validate MonitoringFilters against datatype before installing

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/security/DefaultTrustListManager.java

If last modified of any file changes during the sort it can lead to
"IllegalArgumentException: Comparison method violates its general contract!"
thrown from Java's TimSort implementation.
fixes #617

Create a stable map of last modified values to use while sorting

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/AbstractNodeManager.java

Maintain references in the order they were added (per NodeManager) by using a `LinkedHashMultiset` instead of a `ConcurrentHashMultiset`.

Use LinkedHashMultiset to maintain managed Reference order

---

opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/transport/uasc/UascClientMessageHandler.java
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/channel/ChunkDecoder.java
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/channel/MessageAbortException.java
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/channel/MessageAbortedException.java
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/channel/MessageDecodeException.java
opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/UaStackServer.java
opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/transport/uasc/UascServerAsymmetricHandler.java
opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/transport/uasc/UascServerSymmetricHandler.java
opc-ua-stack/stack-tests/src/test/java/org/eclipse/milo/opcua/stack/ChunkSerializationTest.java
opc-ua-stack/stack-tests/src/test/java/org/eclipse/milo/opcua/stack/SecureChannelFixture.java

Refactor chunk decoding logic to remove the callback and nested try/catch blocks.

Improve error handling while decoding message chunks

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/subscriptions/PublishQueue.java
opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/services/ServiceRequest.java

Check timeoutHint using server time, send Bad_Timeout if it has elapsed

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/subscriptions/Subscription.java

Send Bad_Timeout notification when subscription lifetime expires

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/SessionManager.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/config/OpcUaServerConfigLimits.java

Allow max session timeout to be configured

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/config/OpcUaServerConfig.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/config/OpcUaServerConfigBuilder.java
opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/UaStackServerConfig.java
opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/UaStackServerConfigBuilder.java
opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/transport/uasc/UascServerAsymmetricHandler.java

Allow min/max secure channel lifetime to be configured

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/diagnostics/variables/ServerDiagnosticsSummaryVariable.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/diagnostics/variables/SessionDiagnosticsVariable.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/diagnostics/variables/SessionDiagnosticsVariableArray.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/diagnostics/variables/SessionSecurityDiagnosticsVariable.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/diagnostics/variables/SessionSecurityDiagnosticsVariableArray.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/diagnostics/variables/SubscriptionDiagnosticsVariable.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/diagnostics/variables/SubscriptionDiagnosticsVariableArray.java

Remove AttributeObservers added by diagnostics objects during shutdown

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/security/DefaultTrustListManager.java
opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/security/DefaultTrustListManagerTest.java

Use Long.compareUnsigned when comparing lastModified attributes

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/DefaultNodeManagementServiceSet.java

Implement DefaultNodeManagementServiceSet

---

opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/AddressSpace.java

Log failure and continue when creating a Node fails during AddressSpace::browseNodes

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/ExpandedNodeId.java
opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/types/builtin/ExpandedNodeIdTest.java

Fix parsing of ExpandedNodeId when URI contains "="

---

opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscription.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscriptionManager.java

Track and update available acknowledgements per-subscription

---

opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/UaStackServer.java
opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/services/DiscoveryServiceSet.java

Add FindServersOnNetwork service to DiscoveryServiceSet

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/UaNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/UaPropertyNode.java

Use PropertyTypeNode when implicitly creating property Nodes

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/OpcUaServer.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/config/OpcUaServerConfig.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/config/OpcUaServerConfigBuilder.java
opc-ua-sdk/sdk-server/src/test/java/org/eclipse/milo/opcua/sdk/server/api/config/OpcUaServerConfigTest.java

Allow ScheduledExecutorService used by OpcUaServer to be configured

---

opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/config/OpcUaClientConfig.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/config/OpcUaClientConfigBuilder.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/SessionFsmFactory.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/Session.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/DefaultViewServiceSet.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/helpers/BrowseHelper.java
opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/UaStackClientConfig.java
opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/UaStackClientConfigBuilder.java
opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/transport/AbstractTransport.java
opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/transport/uasc/ClientChannelFsm.java

Allow usages of ExecutorService and ScheduledExecutorService to be configured

---

opc-ua-sdk/dictionary-manager/src/main/java/org/eclipse/milo/opcua/sdk/server/api/DataTypeDictionaryManager.java

Use Namespaces.OPC_UA URI for fields that are built-in structs

---

opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/AddressSpaceTest.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/AddressSpace.java

Return a better error when AddressSpace#getNode fails

---

opc-ua-sdk/dictionary-reader/src/main/java/org/eclipse/milo/opcua/sdk/client/DataTypeDictionaryReader.java

Read namespace 0 dictionary in DataTypeDictionaryReader

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/methods/AbstractMethodInvocationHandler.java

Allow custom structures to be used with AbstractMethodInvocationHandler

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/OpcUaDefaultBinaryEncoding.java

Use un-pooled heap buffer and ensure it's released

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/items/MonitoredDataItem.java

Ensure lastValue is not null before enqueueing it

---

opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/AddressSpaceTest.java
opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/methods/UaMethodTest.java
opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/test/SqrtMethod.java
opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/test/TestNamespace.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/nodes/UaObjectNode.java
opc-ua-sdk/sdk-core/src/main/java/org/eclipse/milo/opcua/sdk/core/Reference.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/UaObjectNode.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/UaObjectTypeNode.java

Ensure methods referenced by HasOrderedComponent are callable

---

milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleServer.java
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/NonceUtil.java
opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/util/NonceUtilTest.java

Allow applications to block until NonceUtil's SecureRandom is seeded

---

opc-ua-sdk/dictionary-reader/src/main/java/org/eclipse/milo/opcua/sdk/client/dtd/DataTypeDictionaryReader.java
opc-ua-sdk/dictionary-reader/src/test/java/org/eclipse/milo/opcua/sdk/client/dtd/DataTypeDictionaryReaderTest.java

Use configured client request timeout in DataTypeDictionaryReader

---

milo-examples/server-examples/pom.xml
opc-ua-sdk/sdk-server/pom.xml

Remove mistaken org.jetbrains:annotations dependencies in sdk-server

---

opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/transport/uasc/UascClientAcknowledgeHandler.java

Implement exceptionCaught() in UascClientAcknowledgeHandler

---

opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/server/api/methods/AbstractMethodInvocationHandlerTest.java
opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/test/TestNamespace.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/methods/AbstractMethodInvocationHandler.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/methods/InvalidArgumentException.java

Allow AbstractMethodInvocationHandler implementations to validate inputs

---

pom.xml

This resolves a ConcurrentModificationException some users see when attempting a build.
fixes #849

Update maven-bundle-plugin to version 5.1.2

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/channel/ChunkDecoder.java

Return Bad_SecurityChecksFailed for unexpected chunk sequence number

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/config/OpcUaServerConfig.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/config/OpcUaServerConfigBuilder.java
opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/UaStackServerConfig.java
opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/UaStackServerConfigBuilder.java
opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/transport/http/OpcServerHttpChannelInitializer.java

Before you submit a pull request please acknowledge the following:
See [CONTRIBUTING](https://github.com/eclipse/milo/blob/master/CONTRIBUTING.md) for more information.

[#870]: Allow setting a certificate chain

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/factories/InstanceDeclarationHierarchy.java

When building an InstanceDeclarationHierarchy, add not only the explicitly
referenced instance declarations but also any instance declarations found
following the Node's type definition, if it has one. This allows optional
nodes not present on the instance declaration to later be instantiated,
if desired, by a NodeFactory.
fixes #873

Recursively add instance declarations from type definitions

---

opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/subscriptions/SubscriptionWatchdogTimerTest.java
opc-ua-sdk/integration-tests/src/test/java/org/eclipse/milo/opcua/sdk/test/TestNamespace.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/subscriptions/UaSubscription.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/subscriptions/UaSubscriptionManager.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/ManagedSubscription.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscriptionManager.java

Implement a client subscription watchdog timer

---

opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/NodeCache.java

Don't modify CacheBuilder in the constructor that accepts Consumer

---

milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleNamespace.java

Set the EnumStrings property after registering CustomEnumType

---

opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/DiscoveryClient.java

Allow customization DiscoveryClient's UaStackClientConfig

---

opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/AddressSpace.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/BrowseHelper.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/DataTypeTreeBuilder.java

Add a maxReferencesPerNode field to BrowseOptions

---

milo-examples/server-examples/src/main/java/org/eclipse/milo/examples/server/ExampleServer.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/config/OpcUaServerConfigBuilder.java

Explain setHttpsCertificate deprecation and update ExampleServer

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/SecureXmlUtil.java

Catch Exceptions setting attributes in SecureXmlUtil

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/security/DefaultTrustListManager.java
opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/security/DefaultTrustListManagerTest.java

Better filename sanitization in DefaultTrustListManager

---

opc-ua-stack/stack-client/src/main/java/org/eclipse/milo/opcua/stack/client/transport/uasc/UascClientMessageHandler.java

Part 6 says the nonce is to be ignored when `MessageSecurityMode` is `None`.
fixes #950

Relax validation of server nonce in OpenSecureChannelResponse

---

opc-ua-stack/pom.xml

Before you submit a pull request please acknowledge the following:
See [CONTRIBUTING](https://github.com/eclipse/milo/blob/master/CONTRIBUTING.md) for more information.

[security] bump netty version to solve cve problems

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/subscriptions/PublishQueue.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/subscriptions/SubscriptionManager.java

Notify AddressSpaces of deleted DataItems when Subscription times out

---

opc-ua-sdk/sdk-core/src/main/java/org/eclipse/milo/opcua/sdk/core/NumericRange.java
opc-ua-sdk/sdk-server/src/test/java/org/eclipse/milo/opcua/sdk/core/NumericRangeTest.java

Return available values when only the upper index is out of bounds

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/services/helpers/BrowseHelper.java

Check for invalid/null BrowseDirection during before browsing

---

opc-ua-stack/pom.xml

Update Netty to version 4.1.77.Final

---

opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/security/DefaultServerCertificateValidator.java

Don't leak information in stack trace when certificate validation fails

---

opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/config/OpcUaClientConfig.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/api/config/OpcUaClientConfigBuilder.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscriptionManager.java
opc-ua-sdk/sdk-tests/src/test/java/org/eclipse/milo/opcua/sdk/client/config/OpcUaClientConfigTest.java

Make the subscription watchdog multiplier configurable

---

opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/session/SessionFsmFactory.java
opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscriptionManager.java

Cancel WatchdogTimers after Session is closed

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/OpcUaServer.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/config/OpcUaServerConfigLimits.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/subscriptions/SubscriptionManager.java

Allow max MonitoredItems to be configured via OpcUaServerConfigLimits

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/channel/ExceptionHandler.java
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/channel/SerializationQueue.java
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/TaskQueue.java
opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/transport/uasc/UascServerAsymmetricHandler.java
opc-ua-stack/stack-server/src/main/java/org/eclipse/milo/opcua/stack/server/transport/uasc/UascServerSymmetricHandler.java

Limit the number of requests that can be queued for deserialization

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/Session.java
opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/api/ManagedAddressSpace.java

Use a semaphore to limit a session's concurrent method calls

---

opc-ua-stack/pom.xml

Update Netty to 4.1.97.Final

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/channel/ChunkDecoder.java
opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/channel/ChunkDecoderTest.java
opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/channel/LegacySequenceNumberValidatorTest.java

Handle rollover in ChunkDecoder sequence validation

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/validation/CertificateValidationUtil.java
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/validation/OpcUaCertificateUsageChecker.java
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/validation/ValidationCheck.java

Remove unnecessary KeyUsage checks against issuer certificates

---

opc-ua-stack/pom.xml

Update Netty to 4.1.105.Final

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/util/ManifestUtil.java

Refactor ManifestUtil, remove conversion to URI

---

opc-ua-sdk/pom.xml
opc-ua-stack/pom.xml

Updates dependencies:
- Guava to 33.2.1
- slf4j to 1.7.36
- Netty to 4.1.112

Misc Dependency Updates

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/servicesets/impl/helpers/BrowseHelper.java

Fix browse regressions, CTT View Basic 008 and 018

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/servicesets/impl/helpers/BrowseHelper.java

Check for invalid BrowseDirection before browsing

---

milo-examples/client-examples/src/main/java/org/eclipse/milo/examples/client/IJTReadCustomDataTypeExample.java
opc-ua-sdk/sdk-core/src/main/java/org/eclipse/milo/opcua/sdk/core/types/DynamicStructType.java
opc-ua-sdk/sdk-core/src/main/java/org/eclipse/milo/opcua/sdk/core/types/PrettyToString.java
opc-ua-sdk/sdk-core/src/main/java/org/eclipse/milo/opcua/sdk/core/types/codec/FieldUtil.java
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/Matrix.java
opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/types/builtin/MatrixTest.java

When an ExtensionObject (scalar, array, or matrix) is encountered, or a Variant containing one of the former, attempt to eagerly decode that ExtensionObject and use the decoded value as the value for that member.

Eagerly decode ExtensionObjects in DynamicStructType

---

opc-ua-stack/transport/src/main/java/org/eclipse/milo/opcua/stack/transport/server/OpcServerTransportConfig.java
opc-ua-stack/transport/src/main/java/org/eclipse/milo/opcua/stack/transport/server/tcp/OpcTcpServerTransport.java
opc-ua-stack/transport/src/main/java/org/eclipse/milo/opcua/stack/transport/server/tcp/OpcTcpServerTransportConfigBuilder.java

Allow customization of ServerBoostrap and ChannelPipeline

---

opc-ua-stack/encoding-json/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/json/OpcUaDefaultJsonEncoding.java
opc-ua-stack/encoding-json/src/main/java/org/eclipse/milo/opcua/stack/core/encoding/json/OpcUaJsonEncoder.java
opc-ua-stack/encoding-json/src/test/java/org/eclipse/milo/opcua/stack/core/encoding/json/OpcUaJsonEncoderTest.java

and make it generally more consistent with OpcUaXmlEncoder.

Implement AutoCloseable in OpcUaJsonEncoder

---

pom.xml

Update netty-channel-fsm to version 1.0.1

---

opc-ua-sdk/codec-json/pom.xml
opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/Stack.java
opc-ua-stack/transport-https/pom.xml
opc-ua-stack/transport-websocket/pom.xml
opc-ua-stack/transport/src/main/java/org/eclipse/milo/opcua/stack/transport/client/tcp/OpcTcpClientTransportConfigBuilder.java
pom.xml

This reverts commit 00d5f2ff
See https://github.com/netty/netty/issues/15003

Revert "Update Netty to version 4.2.0.Final (#1437)"

---

opc-ua-stack/stack-core/src/main/java/org/eclipse/milo/opcua/stack/core/types/builtin/StatusCode.java
opc-ua-stack/stack-core/src/test/java/org/eclipse/milo/opcua/stack/core/StatusCodesTest.java

Add "name" field to `StatusCode::toString`

---

opc-ua-sdk/sdk-client/src/main/java/org/eclipse/milo/opcua/sdk/client/subscriptions/OpcUaSubscription.java

NPEs accessing the `ServerState` were possible in e.g. logging calls that happen from callbacks or other threads after the subscription is deleted, or before it has been created.

Add null checks for `ServerState` in `OpcUaSubscription`

---

opc-ua-sdk/dtd-reader/src/main/java/org/eclipse/milo/opcua/sdk/client/dtd/BinaryDataTypeDictionaryReader.java

Call `maybeBrowseNext` after browsing in `browseNode`

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/Session.java

Follows the established best practice of scheduling a task with the ScheduledExecutorService and then immediately offloading the potentially blocking action to the ExecutorService when it runs.

Run `checkTimeout` on the configured ExecutorService

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/namespaces/OpcUaNamespace.java

Use "Standard 2022 UA Server Profile" by default

---

opc-ua-sdk/sdk-server/src/main/java/org/eclipse/milo/opcua/sdk/server/nodes/UaVariableNode.java

Use Bad_NoValue for the StatusCode of initially null values instead of Uncertain_InitialValue.

Use Bad_NoValue instead of Uncertain_InitialValue
